import type { UserLevel } from "@prisma/client";

export const PERMISSIONS = [
  ["dashboard:view", "View dashboards"],
  ["ticket:view", "View tickets"],
  ["ticket:create", "Create tickets"],
  ["ticket:manage", "Manage department tickets"],
  ["ticket:escalate", "Escalate tickets"],
  ["onboarding:view", "View onboarding cases"],
  ["onboarding:create", "Create onboarding requests"],
  ["onboarding:manage", "Manage onboarding cases"],
  ["onboarding:approve", "Approve onboarding items"],
  ["payroll:view", "View payroll coordination"],
  ["payroll:create", "Create payroll coordination requests"],
  ["payroll:approve", "Approve payroll coordination requests"],
  ["payroll:export", "Generate safe payroll exports"],
  ["timeoff:view", "View time-off requests"],
  ["timeoff:create", "Create time-off requests"],
  ["timeoff:approve", "Approve time-off requests"],
  ["attendance:view", "View attendance and schedule issues"],
  ["attendance:create", "Create attendance and schedule issues"],
  ["attendance:manage", "Manage attendance and schedule issues"],
  ["erp:view", "View internal ERP records"],
  ["erp:create", "Create internal ERP records"],
  ["erp:manage", "Manage internal ERP records"],
  ["erp:export", "Export internal ERP reports"],
  ["employee:view", "View employee records within scope"],
  ["employee:manage", "Manage employee lifecycle records"],
  ["task:view", "View productivity tasks"],
  ["task:create", "Create productivity tasks"],
  ["task:manage", "Manage productivity tasks"],
  ["checklist:manage", "Manage recurring checklists"],
  ["approval:view", "View approval queues"],
  ["approval:decide", "Decide approval requests"],
  ["report:view", "View reports"],
  ["report:export", "Export reports"],
  ["file:upload", "Upload allowed non-sensitive files"],
  ["note:view", "View manager notes within visibility"],
  ["note:manage", "Manage manager notes and follow-ups"],
  ["announcement:manage", "Manage announcements"],
  ["admin:manage", "Manage global settings"],
  ["audit:view", "View audit log"],
  ["sop:ask", "Ask the SOP Knowledge Base assistant"],
  ["sop:author", "Author SOP drafts"],
  ["sop:approve", "Approve SOP versions"],
  ["sop:admin", "Manage the SOP document lifecycle"],
  ["sop:escalation:resolve", "Resolve SOP escalations"],
  ["ai:use", "Use AI-powered features"],
  ["ai:audit", "View AI action audit log"],
  ["quiz:take", "Take training quizzes"],
  ["quiz:launch", "Launch quizzes and create share links"],
  ["quiz:author", "Author quizzes and bank questions"],
  ["quiz:insights", "View quiz insights and reports"],
  ["quiz:admin", "Administer training assessments"],
  ["quote:view", "View quotes within scope"],
  ["quote:create", "Create quote drafts"],
  ["quote:price", "Apply pricing, margins, and approve quote totals"],
  ["quote:submit", "Submit quotes to customers"],
  ["quote:admin", "Administer quote settings and templates"],
  ["cycletime:view", "View cycle-time lookup tables"],
  ["cycletime:manage", "Maintain cycle-time lookup tables"],
  ["jobactual:view", "View recorded job actuals"],
  ["jobactual:record", "Record completed-job actuals (feeds cycle-time estimates)"]
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number][0];

const levelPermissions: Record<UserLevel, PermissionKey[]> = {
  USER: [
    "dashboard:view",
    "ticket:view",
    "ticket:create",
    "onboarding:view",
    "payroll:create",
    "timeoff:view",
    "timeoff:create",
    "attendance:view",
    "attendance:create",
    "erp:view",
    "task:view",
    "file:upload",
    "sop:ask",
    "ai:use",
    "quiz:take",
    "quote:view"
  ],
  MANAGER: [
    "dashboard:view",
    "ticket:view",
    "ticket:create",
    "ticket:manage",
    "ticket:escalate",
    "onboarding:view",
    "onboarding:create",
    "onboarding:manage",
    "payroll:view",
    "payroll:create",
    "timeoff:view",
    "timeoff:approve",
    "attendance:view",
    "attendance:manage",
    "erp:view",
    "erp:create",
    "erp:manage",
    "employee:view",
    "task:view",
    "task:create",
    "task:manage",
    "checklist:manage",
    "approval:view",
    "approval:decide",
    "report:view",
    "file:upload",
    "note:view",
    "note:manage",
    "announcement:manage",
    "sop:ask",
    "sop:author",
    "sop:escalation:resolve",
    "ai:use",
    "quiz:take",
    "quiz:launch",
    "quiz:author",
    "quiz:insights",
    "quote:view",
    "quote:create",
    "quote:price",
    "cycletime:view",
    "jobactual:view",
    "jobactual:record"
  ],
  DIRECTOR: [
    "dashboard:view",
    "ticket:view",
    "ticket:create",
    "ticket:manage",
    "ticket:escalate",
    "onboarding:view",
    "onboarding:create",
    "onboarding:manage",
    "onboarding:approve",
    "payroll:view",
    "payroll:create",
    "payroll:approve",
    "timeoff:view",
    "timeoff:approve",
    "attendance:view",
    "attendance:manage",
    "erp:view",
    "erp:create",
    "erp:manage",
    "erp:export",
    "employee:view",
    "employee:manage",
    "task:view",
    "task:create",
    "task:manage",
    "checklist:manage",
    "approval:view",
    "approval:decide",
    "report:view",
    "report:export",
    "file:upload",
    "note:view",
    "note:manage",
    "announcement:manage",
    "sop:ask",
    "sop:author",
    "sop:approve",
    "sop:escalation:resolve",
    "ai:use",
    "ai:audit",
    "quiz:take",
    "quiz:launch",
    "quiz:author",
    "quiz:insights",
    "quote:view",
    "quote:create",
    "quote:price",
    "quote:submit",
    "cycletime:view",
    "cycletime:manage",
    "jobactual:view",
    "jobactual:record"
  ],
  ADMIN: PERMISSIONS.map(([key]) => key)
};

export function permissionsForLevel(level: UserLevel) {
  return levelPermissions[level];
}

export function can(level: UserLevel, permission: PermissionKey) {
  return permissionsForLevel(level).includes(permission);
}
