import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  FileArchive,
  FileCheck2,
  FileSpreadsheet,
  FolderKanban,
  Gauge,
  Handshake,
  HardHat,
  HelpCircle,
  IdCard,
  Inbox,
  ListChecks,
  NotebookPen,
  PackageCheck,
  PanelTop,
  ScrollText,
  Settings,
  ShieldCheck,
  Timer,
  UserCheck,
  UserCog,
  Users,
  WalletCards,
  Wrench
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const PRODUCT_NAME = process.env.APP_NAME ?? "CleanOps Command Center";
export const SHORT_NAME = "CleanOps";
export const COMMERCIAL_NAME = "CleanOps Command Center";
export const TAGLINE = "ERP · Jobs · Quotes · Inventory · Tickets · Manager Accountability";
export const BRAND_FOOTER = "Faster shops. Cleaner jobs. Accountable work.";
export const DISCLAIMER =
  "This platform supports internal shop ERP operations, department tickets, onboarding, approvals, payroll coordination, checklists, scheduling, inventory, purchasing, shipping, quality coordination, and manager accountability. It is not designed to store CUI, ITAR-controlled data, payment-card data, bank information, full SSNs, medical records, tax credentials, payroll passwords, API keys, cybersecurity secrets, or formal compliance evidence. PCI DSS, CMMC, and other certifications are not guaranteed.";
export const ENCLAVE_COMPATIBLE_STATEMENT =
  "Customers with regulated environments may access this platform from within their own approved secure browser, VDI, or enclave environment, but the customer remains responsible for controlling what data is entered, uploaded, exported, or integrated. This platform is not a CUI enclave and must not be used to store or process CUI unless a future compliant deployment is explicitly designed, contracted, and assessed.";

export const USER_LEVELS = [
  {
    key: "USER",
    label: "User",
    purpose: "Standard employee, shop-floor user, contractor, or general self-service user."
  },
  {
    key: "MANAGER",
    label: "Manager",
    purpose: "Department owner responsible for people, tickets, onboarding, payroll coordination, scheduling issues, productivity, and follow-through."
  },
  {
    key: "DIRECTOR",
    label: "Director",
    purpose: "Cross-department oversight, escalation authority, and operational accountability."
  },
  {
    key: "ADMIN",
    label: "Admin",
    purpose: "Global Admin, CEO, or system owner with full administrative control."
  }
] as const;

export const DEPARTMENTS = [
  { code: "IT", name: "IT", center: "IT Ticket Center" },
  { code: "HR", name: "HR", center: "HR Ticket Center" },
  { code: "PAYROLL", name: "Payroll", center: "Payroll Ticket Center" },
  { code: "MAINT", name: "Maintenance", center: "Maintenance Ticket Center" },
  { code: "QUALITY", name: "Quality", center: "Quality Ticket Center" },
  { code: "ENG", name: "Engineering", center: "Engineering Ticket Center" },
  { code: "PROD", name: "Production", center: "Production Ticket Center" },
  { code: "SHIP", name: "Shipping / Receiving", center: "Shipping / Receiving Ticket Center" },
  { code: "ADMIN", name: "Office / Admin", center: "Office / Admin Ticket Center" },
  { code: "TOOL", name: "Tool Crib", center: "Tool Crib Ticket Center" },
  { code: "PURCH", name: "Purchasing", center: "Purchasing Ticket Center" },
  { code: "FAC", name: "Facilities", center: "Facilities Ticket Center" },
  { code: "SAFETY", name: "Safety", center: "Safety Ticket Center" },
  { code: "MGMT", name: "Management", center: "Management Ticket Center" }
] as const;

export const TICKET_STATUSES = [
  "New",
  "Assigned",
  "In Progress",
  "Waiting on Requester",
  "Waiting on Manager",
  "Waiting on Director",
  "Waiting on External Vendor",
  "Blocked",
  "Escalated",
  "Resolved",
  "Closed",
  "Reopened",
  "Cancelled"
] as const;

export const TICKET_PRIORITIES = ["Low", "Normal", "High", "Urgent", "Work Stoppage"] as const;

export const TICKET_CATEGORIES: Record<string, string[]> = {
  PAYROLL: [
    "missed punch",
    "time correction",
    "pay question",
    "rate change request",
    "bonus request",
    "deduction question",
    "reimbursement request",
    "payroll export issue",
    "PTO balance question",
    "schedule/pay period issue"
  ],
  HR: [
    "onboarding question",
    "document request",
    "policy acknowledgment",
    "employee information update",
    "training assignment",
    "performance documentation",
    "contractor record",
    "employee status change",
    "termination preparation",
    "general HR request"
  ],
  MAINT: [
    "machine issue",
    "facility repair",
    "safety hazard",
    "tool repair",
    "equipment inspection",
    "preventive maintenance",
    "urgent downtime",
    "supplies needed"
  ],
  QUALITY: [
    "inspection issue",
    "nonconformance coordination",
    "document clarification",
    "training needed",
    "customer quality request",
    "calibration coordination",
    "process question"
  ],
  PROD: [
    "job issue",
    "material shortage",
    "schedule conflict",
    "staffing issue",
    "machine assignment",
    "production blocker",
    "overtime request",
    "shift handoff"
  ],
  ENG: [
    "drawing question",
    "programming request",
    "revision clarification",
    "process improvement",
    "fixture request",
    "tooling support",
    "technical review"
  ],
  SHIP: [
    "shipment issue",
    "receiving issue",
    "packing question",
    "carrier issue",
    "customer shipment request",
    "material delivery issue"
  ],
  ADMIN: ["supplies", "visitor coordination", "contact update", "document request", "meeting support", "general admin task"]
};

const defaultCategories = [
  "access request",
  "resource request",
  "department question",
  "manager review",
  "approval needed",
  "blocker",
  "general request"
];

export function categoriesForDepartment(code: string) {
  return TICKET_CATEGORIES[code] ?? defaultCategories;
}

export const PAYROLL_REQUEST_TYPES = [
  "pay rate change",
  "salary adjustment",
  "hourly wage adjustment",
  "bonus",
  "incentive",
  "reimbursement",
  "missed punch correction",
  "time correction",
  "department change",
  "job title change",
  "shift differential",
  "overtime correction",
  "PTO correction",
  "unpaid time note",
  "payroll note",
  "payroll question"
] as const;

export const PAYROLL_STATUSES = [
  "Draft",
  "Submitted",
  "Manager Review",
  "Director Review",
  "Payroll Review",
  "Needs More Info",
  "Approved for Payroll Entry",
  "Exported to Payroll Processor",
  "Completed",
  "Rejected",
  "Cancelled",
  "Archived"
] as const;

export const TIME_OFF_TYPES = [
  "PTO",
  "unpaid time",
  "sick time",
  "bereavement",
  "jury duty",
  "holiday",
  "personal time",
  "partial day",
  "late arrival",
  "early departure",
  "other"
] as const;

export const ATTENDANCE_ISSUE_TYPES = [
  "missed punch",
  "late arrival",
  "early departure",
  "absence",
  "schedule conflict",
  "shift swap",
  "overtime note",
  "unpaid time note",
  "payroll correction needed",
  "manager documentation note"
] as const;

export const ONBOARDING_TYPES = [
  "new hire",
  "contractor",
  "temp worker",
  "intern",
  "rehire",
  "seasonal worker",
  "department transfer",
  "role change",
  "promotion",
  "shift change",
  "location change"
] as const;

export type WorkflowModule = {
  slug: string;
  title: string;
  navLabel: string;
  icon: LucideIcon;
  summary: string;
  owner: string;
  primaryAction: string;
  secondaryAction: string;
  metricLabels: string[];
  workflows: string[];
  fields: string[];
  statuses: string[];
  reports: string[];
};

export const WORKFLOW_MODULES: WorkflowModule[] = [
  {
    slug: "executive-command-dashboard",
    title: "Executive Command Dashboard",
    navLabel: "Command Dashboard",
    icon: Gauge,
    summary: "Company-wide organization health across tickets, onboarding, payroll coordination, approvals, blockers, and manager follow-through.",
    owner: "Global Admin / CEO",
    primaryAction: "Generate Operations Summary",
    secondaryAction: "Open Urgent Queue",
    metricLabels: ["Open tickets", "Overdue tickets", "Payroll readiness", "Onboarding readiness"],
    workflows: ["Company operations health", "Urgent action queue", "Manager accountability leaderboard", "Department health comparison"],
    fields: ["department", "manager", "date range", "filters", "summary metrics", "report ID"],
    statuses: ["Healthy", "Needs Attention", "Blocked", "Escalated"],
    reports: ["Company Operations Summary", "Department Health Report", "Manager Accountability Report"]
  },
  {
    slug: "erp-command-center",
    title: "ERP Command Center",
    navLabel: "ERP Command",
    icon: Gauge,
    summary: "Internal shop ERP command center for customers, quotes, sales orders, work orders, schedules, inventory, purchasing, shipping, quality coordination, and shop-floor time.",
    owner: "Operations, Directors, Global Admin",
    primaryAction: "Create Work Order",
    secondaryAction: "Open Job Queue",
    metricLabels: ["Active jobs", "Late jobs", "Open POs", "Quality queue"],
    workflows: ["Quote to order", "Order to work order", "Material and purchasing", "Shipping and quality handoff"],
    fields: ["customer", "quote", "order", "work order", "part", "quantity", "due date", "owner", "status"],
    statuses: ["Planned", "Released", "In Process", "Blocked", "Ready to Ship", "Closed"],
    reports: ["ERP Operations Summary", "Job Backlog Report", "Shop Readiness Report"]
  },
  {
    slug: "customers-parts",
    title: "Customers & Parts",
    navLabel: "Customers & Parts",
    icon: Handshake,
    summary: "Customer account records and part master records with safe metadata only. No payment cards, banking data, CUI, ITAR-controlled files, or regulated technical data.",
    owner: "Sales, Engineering, Admin",
    primaryAction: "Add Customer",
    secondaryAction: "Add Part",
    metricLabels: ["Customers", "Active parts", "Customer-owned parts", "Needs review"],
    workflows: ["Create account", "Create part", "Link customer", "Archive obsolete record"],
    fields: ["account number", "customer", "contact", "part number", "revision", "description", "make/buy"],
    statuses: ["ACTIVE", "HOLD", "ARCHIVED"],
    reports: ["Customer Account Report", "Part Master Report"]
  },
  {
    slug: "quotes-orders",
    title: "Quotes & Orders",
    navLabel: "Quotes & Orders",
    icon: FileSpreadsheet,
    summary: "Quote and sales-order tracking with safe estimated values, customer PO references, promised dates, and order handoff visibility.",
    owner: "Sales, Operations",
    primaryAction: "Create Quote",
    secondaryAction: "Create Sales Order",
    metricLabels: ["Open quotes", "Orders open", "Quotes due", "Orders at risk"],
    workflows: ["Estimate quote", "Review quote", "Create order", "Release job"],
    fields: ["quote number", "customer", "title", "due date", "estimated value", "order number", "promised date"],
    statuses: ["DRAFT", "IN_REVIEW", "SENT", "OPEN", "RELEASED", "CLOSED"],
    reports: ["Quote Aging Report", "Sales Order Readiness Report"]
  },
  {
    slug: "jobs-work-orders",
    title: "Jobs & Work Orders",
    navLabel: "Jobs & Work Orders",
    icon: Wrench,
    summary: "Production work orders and operation routing with job status, material status, quality status, schedule status, ownership, and due dates.",
    owner: "Production, Operations",
    primaryAction: "Create Work Order",
    secondaryAction: "Add Operation",
    metricLabels: ["Active jobs", "Late jobs", "Blocked jobs", "Operations queued"],
    workflows: ["Create work order", "Add router operation", "Assign work center", "Close job"],
    fields: ["work order", "part", "customer", "quantity", "operation", "work center", "due date", "status"],
    statuses: ["PLANNED", "RELEASED", "IN_PROCESS", "BLOCKED", "COMPLETE", "CLOSED"],
    reports: ["Job Backlog Report", "Operation Queue Report", "Late Work Order Report"]
  },
  {
    slug: "shop-schedule",
    title: "Shop Schedule",
    navLabel: "Shop Schedule",
    icon: CalendarClock,
    summary: "Work-center schedule and dispatch board for scheduled jobs, priorities, coverage signals, and work stoppage visibility.",
    owner: "Operations, Managers",
    primaryAction: "Schedule Work",
    secondaryAction: "Review Dispatch",
    metricLabels: ["Scheduled", "Work centers", "Work stoppage", "Due today"],
    workflows: ["Schedule operation", "Assign owner", "Review priority", "Update status"],
    fields: ["work order", "operation", "work center", "schedule date", "priority", "owner"],
    statuses: ["SCHEDULED", "RUNNING", "HOLD", "COMPLETE", "CANCELLED"],
    reports: ["Shop Schedule Report", "Work Center Load Report"]
  },
  {
    slug: "inventory-materials",
    title: "Inventory & Materials",
    navLabel: "Inventory",
    icon: PackageCheck,
    summary: "Inventory item records, material quantities, allocations, reorder points, locations, and low-stock visibility for internal operations.",
    owner: "Materials, Purchasing, Operations",
    primaryAction: "Add Inventory Item",
    secondaryAction: "Review Low Stock",
    metricLabels: ["Items", "Allocated", "Low stock", "Locations"],
    workflows: ["Create item", "Allocate material", "Review reorder", "Adjust status"],
    fields: ["item number", "part", "description", "on hand", "allocated", "reorder point", "location"],
    statuses: ["ACTIVE", "LOW_STOCK", "HOLD", "ARCHIVED"],
    reports: ["Inventory Summary", "Low Stock Report", "Material Allocation Report"]
  },
  {
    slug: "purchasing-receiving",
    title: "Purchasing & Receiving",
    navLabel: "Purchasing",
    icon: PackageCheck,
    summary: "Vendor records, purchase orders, expected dates, receiving records, material follow-up, and purchasing accountability.",
    owner: "Purchasing, Receiving",
    primaryAction: "Create Purchase Order",
    secondaryAction: "Record Receipt",
    metricLabels: ["Open POs", "Late POs", "Vendors", "Receipts"],
    workflows: ["Create vendor", "Create PO", "Track expected date", "Record receipt"],
    fields: ["vendor", "PO number", "expected date", "estimated total", "receipt number", "status"],
    statuses: ["DRAFT", "ORDERED", "PARTIAL", "RECEIVED", "LATE", "CLOSED"],
    reports: ["Purchase Order Report", "Receiving Report", "Vendor Follow-Up Report"]
  },
  {
    slug: "shipping",
    title: "Shipping",
    navLabel: "Shipping",
    icon: PackageCheck,
    summary: "Shipment planning for customer orders and work orders with carrier, tracking, ship date, readiness, and hold visibility.",
    owner: "Shipping / Receiving",
    primaryAction: "Plan Shipment",
    secondaryAction: "Review Holds",
    metricLabels: ["Planned", "Ready", "On hold", "Shipped"],
    workflows: ["Plan shipment", "Link order", "Record tracking", "Mark shipped"],
    fields: ["shipment number", "customer", "order", "work order", "carrier", "tracking", "ship date"],
    statuses: ["PLANNED", "READY", "HOLD", "SHIPPED", "CANCELLED"],
    reports: ["Shipment Board Report", "Shipping Readiness Report"]
  },
  {
    slug: "quality-ncrs",
    title: "Quality & NCRs",
    navLabel: "Quality",
    icon: ClipboardCheck,
    summary: "Inspection queues and nonconformance coordination for internal production control. Not a formal compliance evidence or certification system.",
    owner: "Quality Manager",
    primaryAction: "Create Inspection",
    secondaryAction: "Create NCR",
    metricLabels: ["Inspections", "Open NCRs", "Holds", "Completed"],
    workflows: ["Queue inspection", "Record result", "Create NCR", "Disposition issue"],
    fields: ["inspection number", "work order", "part", "inspection type", "result", "NCR", "severity", "disposition"],
    statuses: ["PENDING", "IN_PROGRESS", "PASS", "FAIL", "OPEN", "DISPOSITION", "CLOSED"],
    reports: ["Inspection Queue Report", "NCR Summary Report"]
  },
  {
    slug: "shop-floor-control",
    title: "Shop Floor Control",
    navLabel: "Shop Floor",
    icon: Timer,
    summary: "Shop-floor work view and job time entries for operational visibility and job costing. Time entries are not payroll processing.",
    owner: "Employees, Managers",
    primaryAction: "Submit Time Entry",
    secondaryAction: "Review My Work",
    metricLabels: ["Visible jobs", "Scheduled items", "Time entries", "Hours logged"],
    workflows: ["View scheduled work", "Submit time", "Add work notes", "Manager review"],
    fields: ["employee", "work order", "operation", "entry date", "hours", "notes", "status"],
    statuses: ["SUBMITTED", "REVIEWED", "APPROVED", "REJECTED"],
    reports: ["Shop Floor Time Report", "Job Time Summary"]
  },
  {
    slug: "maintenance-command",
    title: "Maintenance Command",
    navLabel: "Maintenance",
    icon: Wrench,
    summary: "Equipment asset register, preventive-maintenance schedule, maintenance work orders, MRO parts/supplies, and downtime log. Operational metadata only — no CUI, ITAR, or proprietary process parameters.",
    owner: "Maintenance, Facilities, Operations",
    primaryAction: "New Maintenance Work Order",
    secondaryAction: "Open PM Schedule",
    metricLabels: ["Machines", "Machines down", "PM due (7d)", "Open work orders"],
    workflows: ["Report a machine issue", "Triage and assign work orders", "Complete scheduled PM", "Track downtime and MRO stock"],
    fields: ["machine", "category", "status", "priority", "assignee", "due date", "frequency", "reorder point"],
    statuses: ["REQUESTED", "ASSIGNED", "IN_PROGRESS", "DONE"],
    reports: ["Machine Roster", "PM Compliance Report", "Downtime Report", "Low MRO Stock Report"]
  },
  {
    slug: "shift-handoff",
    title: "Shift Handoff",
    navLabel: "Shift Handoff",
    icon: ClipboardCheck,
    summary: "End-of-shift handoff log: per-machine status, work order, parts made vs target, and notes for the next shift. DOWN reports flow into the maintenance board.",
    owner: "Operators, Shift Leads, Operations",
    primaryAction: "Submit Handoff",
    secondaryAction: "Review Last Shift",
    metricLabels: ["Handoffs (7d)", "DOWN reports", "Parts made", "Attainment"],
    workflows: ["Submit end-of-shift handoff", "Review previous shift", "Machine DOWN escalation", "Supervisor notification"],
    fields: ["shift", "date", "operators", "machine", "work order", "status", "parts made", "parts target", "notes"],
    statuses: ["RUNNING", "DOWN", "SETUP", "IDLE", "COMPLETE"],
    reports: ["Shift Handoff Log", "Shift Attainment Report"]
  },
  {
    slug: "erp-documents",
    title: "ERP Document Records",
    navLabel: "ERP Documents",
    icon: ScrollText,
    summary: "Safe document metadata and revision records for operational use. Files or metadata must not contain CUI, ITAR data, secrets, PHI, or compliance evidence packets.",
    owner: "Engineering, Quality, Admin",
    primaryAction: "Add Document Record",
    secondaryAction: "Review Revisions",
    metricLabels: ["Documents", "Revisions", "Linked records", "Needs review"],
    workflows: ["Create document record", "Link related record", "Update revision", "Archive obsolete metadata"],
    fields: ["document number", "title", "type", "revision", "related record", "visibility", "status"],
    statuses: ["ACTIVE", "NEEDS_REVIEW", "ARCHIVED"],
    reports: ["Document Metadata Report", "Revision Summary"]
  },
  {
    slug: "director-oversight-dashboard",
    title: "Director Oversight Dashboard",
    navLabel: "Director Oversight",
    icon: PanelTop,
    summary: "Cross-department dashboard for bottlenecks, manager productivity, escalated issues, payroll approvals, and workforce readiness.",
    owner: "Director",
    primaryAction: "Approve Escalation",
    secondaryAction: "Request Manager Update",
    metricLabels: ["Departments watched", "Escalations", "Payroll approvals", "Manager tasks overdue"],
    workflows: ["Reassign ownership", "Approve exceptions", "Review manager KPIs", "Resolve bottlenecks"],
    fields: ["department", "manager", "approval type", "escalation reason", "director note"],
    statuses: ["Pending", "Approved", "Needs Update", "Resolved"],
    reports: ["Director Oversight Report", "Department Workload Report", "Escalation Report"]
  },
  {
    slug: "manager-dashboard",
    title: "Manager Dashboard",
    navLabel: "Manager Dashboard",
    icon: BriefcaseBusiness,
    summary: "Department command center for tickets, onboarding, payroll requests, time-off, attendance, recurring checklists, blockers, and follow-ups.",
    owner: "Manager",
    primaryAction: "Create Department Ticket",
    secondaryAction: "Create Follow-Up",
    metricLabels: ["Open department tickets", "Waiting on manager", "New hires starting", "Follow-ups due"],
    workflows: ["Assign tasks", "Approve time-off", "Submit payroll request", "Escalate issue"],
    fields: ["department", "owner", "due date", "priority", "linked employee", "status"],
    statuses: ["New", "Waiting on Manager", "Blocked", "Complete"],
    reports: ["Manager Weekly Summary", "Department Productivity Report", "Manager Follow-Up Report"]
  },
  {
    slug: "level-1-user-portal",
    title: "Level 1 User Portal",
    navLabel: "Employee Portal",
    icon: UserCheck,
    summary: "Simple employee portal for personal tasks, tickets, onboarding steps, payroll questions, time-off, schedule issues, training, and documents.",
    owner: "Level 1 User",
    primaryAction: "Submit Request",
    secondaryAction: "Complete Task",
    metricLabels: ["My open tickets", "My tasks", "My time-off requests", "My documents"],
    workflows: ["Submit ticket", "Submit payroll question", "Acknowledge document", "View request status"],
    fields: ["request type", "title", "description", "department", "attachment", "comments"],
    statuses: ["Submitted", "In Progress", "Waiting", "Complete"],
    reports: ["Employee Task Report", "Training Assignment Report", "Policy Acknowledgment Report"]
  },
  {
    slug: "department-ticket-centers",
    title: "Department Ticket Centers",
    navLabel: "Department Tickets",
    icon: Inbox,
    summary: "Separate department ticket queues with ownership rules, categories, due dates, comments, internal notes, attachments, escalations, and aging reports.",
    owner: "Managers, Directors, Global Admin",
    primaryAction: "Create Ticket",
    secondaryAction: "Bulk Update",
    metricLabels: ["Open", "Overdue", "Work stoppage", "Average resolution"],
    workflows: ["Assign ticket", "Transfer department", "Add internal note", "Reopen closed ticket"],
    fields: ["ticket ID", "department", "category", "requested by", "assigned owner", "priority", "status", "due date"],
    statuses: [...TICKET_STATUSES],
    reports: ["Ticket Aging Report", "Department Backlog Report", "Owner Workload Report"]
  },
  {
    slug: "onboarding-request-center",
    title: "Onboarding Request Center",
    navLabel: "Onboarding Requests",
    icon: UserCog,
    summary: "Manager-initiated onboarding requests for new hires, contractors, temps, interns, rehires, role changes, transfers, and shift/location changes.",
    owner: "Manager",
    primaryAction: "Create Onboarding Request",
    secondaryAction: "Apply Template",
    metricLabels: ["Drafts", "Submitted", "Missing info", "Ready for HR"],
    workflows: ["Duplicate detection", "Missing information warnings", "Template task generation", "Approval routing"],
    fields: ["first name", "last name", "department", "job title", "manager", "start date", "shift", "location"],
    statuses: ["Draft", "Submitted", "Manager Review", "Director Review", "HR Review"],
    reports: ["Onboarding Readiness Report", "First-Day Readiness Report"]
  },
  {
    slug: "onboarding-case-management",
    title: "Onboarding Case Management",
    navLabel: "Onboarding Cases",
    icon: ClipboardCheck,
    summary: "Full onboarding case detail with payroll coordination, equipment, workspace, training, acknowledgments, milestones, tasks, tickets, blockers, approvals, and timeline.",
    owner: "HR, Manager, Director",
    primaryAction: "Update Case Status",
    secondaryAction: "Generate Summary",
    metricLabels: ["Readiness score", "Tasks complete", "Blockers", "Milestones due"],
    workflows: ["Create payroll handoff", "Create equipment request", "Add blocker", "Escalate to director"],
    fields: ["employee summary", "job details", "readiness", "approvals", "documents", "audit history"],
    statuses: ["Payroll Setup Pending", "Ready for First Day", "Active Onboarding", "30-Day Review", "Complete"],
    reports: ["First-Week Readiness Report", "30/60/90-Day Review Report"]
  },
  {
    slug: "contractor-temp-worker-onboarding",
    title: "Contractor / Temp Worker Onboarding",
    navLabel: "Contractor Onboarding",
    icon: IdCard,
    summary: "Scoped onboarding for contractors and temp workers with start/end tracking, access requests, equipment, training, acknowledgments, and expiration reminders.",
    owner: "Manager, HR",
    primaryAction: "Create Contractor Case",
    secondaryAction: "Review Expirations",
    metricLabels: ["Active contractors", "Starting soon", "Expiring soon", "Missing setup"],
    workflows: ["Create limited-access checklist", "Track extension", "Coordinate badge/key", "Archive completed contract"],
    fields: ["contractor name", "vendor company", "department", "manager", "start date", "end date", "access summary"],
    statuses: ["Draft", "Submitted", "Setup Pending", "Active", "Expiring", "Archived"],
    reports: ["Contractor Expiration Report", "Workforce Readiness Brief"]
  },
  {
    slug: "rehire-workflow",
    title: "Rehire Workflow",
    navLabel: "Rehire Workflow",
    icon: Handshake,
    summary: "Rehire requests with previous employee lookup, approval routing, refreshed onboarding tasks, payroll coordination handoff, and manager readiness tracking.",
    owner: "Manager, HR, Director",
    primaryAction: "Start Rehire",
    secondaryAction: "Review Previous Record",
    metricLabels: ["Pending rehires", "Director review", "Ready for first day", "Blocked"],
    workflows: ["Review prior profile", "Create rehire request", "Generate rehire checklist", "Link lifecycle event"],
    fields: ["employee", "department", "proposed start date", "manager", "reason", "approval history"],
    statuses: ["Submitted", "Manager Review", "Director Review", "HR Review", "Ready"],
    reports: ["Employee Lifecycle Report", "Onboarding Readiness Report"]
  },
  {
    slug: "transfer-role-change-workflow",
    title: "Transfer / Role Change Workflow",
    navLabel: "Transfers & Role Changes",
    icon: Users,
    summary: "Structured department transfers, promotions, shift changes, manager changes, and job title changes with approvals and payroll coordination records.",
    owner: "Manager, Director",
    primaryAction: "Create Change Request",
    secondaryAction: "Route Approval",
    metricLabels: ["Open changes", "Payroll handoffs", "Director approvals", "Effective this week"],
    workflows: ["Request transfer", "Request role change", "Create lifecycle event", "Notify departments"],
    fields: ["employee", "from department", "to department", "effective date", "reason", "payroll impact"],
    statuses: ["Submitted", "Manager Review", "Director Review", "Payroll Review", "Complete"],
    reports: ["Employee Lifecycle Report", "Payroll Coordination Summary"]
  },
  {
    slug: "payroll-coordination-center",
    title: "Payroll Coordination Center",
    navLabel: "Payroll Coordination",
    icon: WalletCards,
    summary: "Payroll coordination workflows for safe change requests, time corrections, bonuses, reimbursements, review checklists, approvals, and limited exports.",
    owner: "Payroll Admin, Manager, Director",
    primaryAction: "Create Payroll Request",
    secondaryAction: "Review Period Checklist",
    metricLabels: ["Pending approvals", "Needs payroll review", "Export ready", "Exceptions"],
    workflows: ["Submit pay change", "Director approve", "Payroll review", "Generate safe export"],
    fields: ["request ID", "employee", "request type", "effective date", "business reason", "approval history", "export status"],
    statuses: [...PAYROLL_STATUSES],
    reports: ["Payroll Coordination Summary", "Pending Payroll Approval Report", "Payroll Period Readiness Report"]
  },
  {
    slug: "time-off-request-center",
    title: "Time-Off Request Center",
    navLabel: "Time-Off Requests",
    icon: CalendarClock,
    summary: "Time-off request coordination with coverage notes, blackout warnings, manager decisions, payroll handoff flags, and request history.",
    owner: "Employee, Manager",
    primaryAction: "Submit Time-Off Request",
    secondaryAction: "Review Team Calendar",
    metricLabels: ["Submitted", "Needs coverage", "Approved", "Payroll notified"],
    workflows: ["Employee submit", "Manager review", "Coverage check", "Export summary"],
    fields: ["employee", "time-off type", "start date", "end date", "coverage plan", "payroll note required"],
    statuses: ["Draft", "Submitted", "Manager Review", "Approved", "Rejected", "Needs Coverage Plan", "Payroll Notified", "Completed", "Cancelled"],
    reports: ["Time-Off Request Report", "Department Coverage Report"]
  },
  {
    slug: "attendance-schedule-issue-center",
    title: "Attendance & Schedule Issue Center",
    navLabel: "Attendance & Schedule",
    icon: Timer,
    summary: "Non-sensitive attendance coordination for missed punches, late arrivals, absences, shift swaps, overtime notes, and payroll correction handoffs.",
    owner: "Employee, Manager, Payroll",
    primaryAction: "Submit Schedule Issue",
    secondaryAction: "Generate Payroll Ticket",
    metricLabels: ["Needs manager review", "Payroll impact", "Recurring issues", "Resolved"],
    workflows: ["Self-submit issue", "Manager review", "Payroll handoff", "Export attendance summary"],
    fields: ["employee", "issue type", "date", "shift", "description", "correction needed", "payroll impact"],
    statuses: ["Submitted", "Manager Review", "Payroll Handoff", "Resolved", "Cancelled"],
    reports: ["Attendance Issue Report", "Time Correction Report"]
  },
  {
    slug: "employee-lifecycle-records",
    title: "Employee Lifecycle Records",
    navLabel: "Employee Lifecycle",
    icon: FileCheck2,
    summary: "Non-sensitive lifecycle events for onboarding, role changes, manager changes, training assignments, attendance notes, milestones, contractor extensions, and exit handoffs.",
    owner: "Manager, HR, Director",
    primaryAction: "Add Lifecycle Event",
    secondaryAction: "Link Related Record",
    metricLabels: ["Open events", "Pending milestones", "Role changes", "Contractor expirations"],
    workflows: ["Create event", "Restrict visibility", "Link tickets", "Export lifecycle report"],
    fields: ["employee", "event type", "department", "manager", "effective date", "visibility", "related records"],
    statuses: ["Open", "In Review", "Complete", "Archived"],
    reports: ["Employee Lifecycle Report", "Contractor Expiration Report"]
  },
  {
    slug: "manager-task-board",
    title: "Manager Task Board",
    navLabel: "Manager Tasks",
    icon: FolderKanban,
    summary: "Manager-owned task board for due dates, priorities, linked employees, linked onboarding cases, tickets, payroll requests, blockers, and completion notes.",
    owner: "Manager",
    primaryAction: "Create Task",
    secondaryAction: "Assign Owner",
    metricLabels: ["Due today", "Overdue", "Blocked", "Needs review"],
    workflows: ["Create task", "Link ticket", "Add blocker", "Approve completion"],
    fields: ["title", "owner", "assigned by", "department", "priority", "due date", "status"],
    statuses: ["Not Started", "In Progress", "Waiting", "Blocked", "Needs Review", "Complete", "Cancelled", "Archived"],
    reports: ["Employee Task Report", "Manager Weekly Summary"]
  },
  {
    slug: "department-productivity-board",
    title: "Department Productivity Board",
    navLabel: "Productivity Board",
    icon: BarChart3,
    summary: "Kanban/table hybrid for Today, This Week, Overdue, Waiting, Blocked, New Hires, Payroll Items, Time-Off, Tickets, Follow-Ups, and Completed.",
    owner: "Manager",
    primaryAction: "Create Board Item",
    secondaryAction: "Switch View",
    metricLabels: ["Today", "This week", "Overdue", "Completed"],
    workflows: ["View by workload", "Move status", "Link request", "Export productivity report"],
    fields: ["task", "owner", "priority", "linked employee", "blocker reason", "completion notes"],
    statuses: ["Not Started", "In Progress", "Waiting", "Blocked", "Needs Review", "Complete"],
    reports: ["Department Productivity Report", "Blocked Items Report"]
  },
  {
    slug: "recurring-checklist-center",
    title: "Recurring Checklist Center",
    navLabel: "Recurring Checklists",
    icon: ListChecks,
    summary: "Recurring daily, weekly, and monthly manager checklists with due times, required evidence, missed checklist behavior, and escalation rules.",
    owner: "Manager, Admin",
    primaryAction: "Create Checklist",
    secondaryAction: "Record Completion",
    metricLabels: ["Due today", "Missed", "Evidence required", "Escalated"],
    workflows: ["Configure checklist", "Assign owner role", "Complete items", "Escalate missed checklist"],
    fields: ["checklist name", "department", "owner role", "frequency", "due time", "items", "evidence required"],
    statuses: ["Active", "Due", "Complete", "Missed", "Escalated", "Inactive"],
    reports: ["Recurring Checklist Completion Report", "Department Health Report"]
  },
  {
    slug: "approval-queue",
    title: "Approval Queue",
    navLabel: "Approvals",
    icon: BadgeCheck,
    summary: "Central approval queue for onboarding, payroll, pay adjustments, reimbursement, time-off, equipment, purchases, contractor extensions, role changes, transfers, and task completion.",
    owner: "Managers, Directors, Payroll Admins, Global Admins",
    primaryAction: "Review Approval",
    secondaryAction: "Request More Info",
    metricLabels: ["Pending", "Needs more info", "Escalated", "Overdue"],
    workflows: ["No self-approval", "Step routing", "Decision logging", "Global override with reason"],
    fields: ["approval type", "source record", "requester", "approver", "decision", "reason", "audit trail"],
    statuses: ["Pending", "Approved", "Rejected", "Needs More Info", "Escalated", "Cancelled", "Expired"],
    reports: ["Pending Payroll Approval Report", "Escalation Report"]
  },
  {
    slug: "escalation-queue",
    title: "Escalation Queue",
    navLabel: "Escalations",
    icon: AlertTriangle,
    summary: "Escalated blockers and requests that need director or executive attention, with source links, reasons, owner reassignment, and resolution notes.",
    owner: "Director, Global Admin",
    primaryAction: "Resolve Escalation",
    secondaryAction: "Reassign Owner",
    metricLabels: ["Open escalations", "Overdue", "Work stoppage", "Resolved this week"],
    workflows: ["Escalate source item", "Assign director", "Request manager update", "Close with reason"],
    fields: ["source type", "source ID", "department", "reason", "escalated by", "escalated to"],
    statuses: ["Open", "Waiting on Manager", "Waiting on Director", "Resolved", "Cancelled"],
    reports: ["Escalation Report", "Blocked Items Report"]
  },
  {
    slug: "employee-directory",
    title: "Employee Directory",
    navLabel: "Employee Directory",
    icon: Users,
    summary: "Role-restricted employee directory with safe profile summaries, department, manager, shift, location, job title, and lifecycle links.",
    owner: "All authenticated users with scope limits",
    primaryAction: "Find Employee",
    secondaryAction: "Open Lifecycle",
    metricLabels: ["Employees", "Departments", "Contractors", "Onboarding"],
    workflows: ["Search", "Filter by department", "View safe summary", "Open related requests"],
    fields: ["employee ID", "name", "department", "manager", "job title", "shift", "location"],
    statuses: ["Active", "Onboarding", "Contractor", "Archived"],
    reports: ["Company Workforce Readiness Brief", "Employee Lifecycle Report"]
  },
  {
    slug: "department-directory",
    title: "Department Directory",
    navLabel: "Department Directory",
    icon: Building2,
    summary: "Directory of departments, managers, directors, ticket centers, locations, teams, and operational ownership.",
    owner: "Global Admin, Directors",
    primaryAction: "Open Department",
    secondaryAction: "Review Ticket Center",
    metricLabels: ["Departments", "Ticket centers", "Managers", "Locations"],
    workflows: ["Assign manager", "Assign director", "Review queue", "Generate department report"],
    fields: ["department", "code", "manager", "director", "location", "ticket center"],
    statuses: ["Active", "Needs Owner", "Archived"],
    reports: ["Department Health Report", "Department Ticket Backlog Report"]
  },
  {
    slug: "contact-directory",
    title: "Contact Directory",
    navLabel: "Contact Directory",
    icon: HelpCircle,
    summary: "Internal contact directory for department owners, request routes, support contacts, vendors, and escalation contacts.",
    owner: "Admin, Managers",
    primaryAction: "Add Contact",
    secondaryAction: "Update Route",
    metricLabels: ["Contacts", "Departments", "Vendors", "Escalation contacts"],
    workflows: ["Find owner", "Route request", "Update contact", "Archive contact"],
    fields: ["name", "department", "role", "phone", "email", "route type"],
    statuses: ["Active", "Needs Update", "Archived"],
    reports: ["Department Directory Export", "Contact Update Report"]
  },
  {
    slug: "equipment-supplies-request-center",
    title: "Equipment & Supplies Request Center",
    navLabel: "Equipment & Supplies",
    icon: PackageCheck,
    summary: "Requests for equipment, supplies, PPE, tools, workspace readiness, badge/key needs, software coordination, and resource approvals.",
    owner: "Employee, Manager, Purchasing, Facilities",
    primaryAction: "Create Resource Request",
    secondaryAction: "Link Onboarding Case",
    metricLabels: ["Submitted", "Pending approval", "Waiting vendor", "Ready"],
    workflows: ["Submit request", "Manager approval", "Assign owner", "Record handoff"],
    fields: ["request ID", "requested by", "requested for", "department", "priority", "due date", "status"],
    statuses: ["Submitted", "Manager Review", "Waiting Vendor", "Ready", "Complete", "Cancelled"],
    reports: ["Equipment Request Report", "Department Productivity Report"]
  },
  {
    slug: "training-assignment-center",
    title: "Training Assignment Center",
    navLabel: "Training Assignments",
    icon: ClipboardList,
    summary: "Training assignments tied to employees, onboarding cases, departments, due dates, completion notes, and manager follow-up.",
    owner: "Manager, HR",
    primaryAction: "Assign Training",
    secondaryAction: "Review Overdue",
    metricLabels: ["Assigned", "Due soon", "Overdue", "Complete"],
    workflows: ["Assign training", "Track completion", "Link onboarding case", "Notify manager"],
    fields: ["employee", "training", "assigned by", "due date", "completion date", "status"],
    statuses: ["Assigned", "In Progress", "Complete", "Overdue", "Cancelled"],
    reports: ["Training Assignment Report", "First-Week Readiness Report"]
  },
  {
    slug: "policy-document-acknowledgment-center",
    title: "Policy / Document Acknowledgment Center",
    navLabel: "Document Acknowledgments",
    icon: ScrollText,
    summary: "Policy and document assignments with acknowledgment tracking, due dates, allowed uploads, and employee visibility.",
    owner: "HR, Manager, Admin",
    primaryAction: "Assign Document",
    secondaryAction: "Review Acknowledgments",
    metricLabels: ["Assigned", "Acknowledged", "Overdue", "Needs review"],
    workflows: ["Assign policy", "Employee acknowledge", "Track due date", "Export acknowledgment report"],
    fields: ["employee", "policy", "file", "assigned by", "due date", "acknowledged at"],
    statuses: ["Assigned", "Acknowledged", "Overdue", "Cancelled"],
    reports: ["Policy Acknowledgment Report", "Onboarding Readiness Report"]
  },
  {
    slug: "manager-notes-follow-ups",
    title: "Manager Notes & Follow-Ups",
    navLabel: "Manager Notes",
    icon: NotebookPen,
    summary: "Structured manager notes with visibility levels, follow-up dates, linked tasks, linked tickets, onboarding cases, and audit history.",
    owner: "Manager, Director, HR/Admin",
    primaryAction: "Create Note",
    secondaryAction: "Create Follow-Up",
    metricLabels: ["Follow-ups due", "Private notes", "Director visible", "Employee visible"],
    workflows: ["Record one-on-one note", "Add coaching note", "Create follow-up", "Restrict visibility"],
    fields: ["employee", "manager", "note type", "title", "visibility", "follow-up required", "follow-up date"],
    statuses: ["Open", "Follow-Up Due", "Complete", "Archived"],
    reports: ["Manager Follow-Up Report", "Employee Lifecycle Report"]
  },
  {
    slug: "meeting-notes-action-items",
    title: "Meeting Notes & Action Items",
    navLabel: "Meeting Actions",
    icon: FileSpreadsheet,
    summary: "Meeting notes and assigned action items with owners, due dates, linked commitments, departments, and completion tracking.",
    owner: "Managers, Directors",
    primaryAction: "Create Meeting Note",
    secondaryAction: "Assign Action Item",
    metricLabels: ["Open action items", "Overdue", "Completed", "Linked commitments"],
    workflows: ["Capture meeting", "Assign action", "Link task", "Close commitment"],
    fields: ["meeting title", "date", "attendees", "summary", "owner", "due date"],
    statuses: ["Open", "Waiting", "Complete", "Archived"],
    reports: ["Manager Weekly Summary", "Department Productivity Report"]
  },
  {
    slug: "one-on-one-tracker",
    title: "One-on-One Tracker",
    navLabel: "One-on-Ones",
    icon: UserCheck,
    summary: "Manager one-on-one tracking with employee, meeting date, notes, action items, visibility, and lifecycle links.",
    owner: "Manager",
    primaryAction: "Record One-on-One",
    secondaryAction: "Schedule Follow-Up",
    metricLabels: ["Due this week", "Completed", "Action items", "Overdue follow-ups"],
    workflows: ["Record conversation", "Create action item", "Create lifecycle event", "Set follow-up"],
    fields: ["employee", "manager", "meeting date", "summary", "action items", "visibility"],
    statuses: ["Scheduled", "Complete", "Follow-Up Due", "Archived"],
    reports: ["Manager Follow-Up Report", "Employee Lifecycle Report"]
  },
  {
    slug: "department-goals",
    title: "Department Goals",
    navLabel: "Department Goals",
    icon: Activity,
    summary: "Department goals and commitments tied to managers, target dates, progress scores, blockers, and executive reporting.",
    owner: "Manager, Director",
    primaryAction: "Create Goal",
    secondaryAction: "Update Progress",
    metricLabels: ["Active goals", "At risk", "Blocked", "Complete"],
    workflows: ["Set goal", "Track score", "Add blocker", "Report progress"],
    fields: ["department", "owner", "title", "target date", "score", "status"],
    statuses: ["Active", "At Risk", "Blocked", "Complete", "Archived"],
    reports: ["Department Health Report", "Director Oversight Report"]
  },
  {
    slug: "internal-announcements",
    title: "Internal Announcements",
    navLabel: "Announcements",
    icon: Bell,
    summary: "Internal announcements targeted by audience, department, or company-wide scope with publish and expiration tracking.",
    owner: "Managers, Directors, Global Admin",
    primaryAction: "Create Announcement",
    secondaryAction: "Publish",
    metricLabels: ["Drafts", "Published", "Expiring", "Archived"],
    workflows: ["Draft", "Target audience", "Publish", "Archive"],
    fields: ["title", "body", "audience", "department", "published at", "expires at"],
    statuses: ["Draft", "Published", "Expired", "Archived"],
    reports: ["Announcement History", "Workforce Readiness Brief"]
  },
  {
    slug: "reports-exports",
    title: "Reports & Exports",
    navLabel: "Reports & Exports",
    icon: FileArchive,
    summary: "Branded internal reports and exports for operations, tickets, payroll coordination, onboarding, attendance, lifecycle events, blockers, and productivity.",
    owner: "Managers, Directors, Global Admin",
    primaryAction: "Generate Report",
    secondaryAction: "Export",
    metricLabels: ["Generated", "Exports", "Templates", "Scheduled"],
    workflows: ["Select report", "Apply filters", "Generate summary", "Export safe fields"],
    fields: ["report title", "report type", "timestamp", "generated by", "date range", "filters", "report ID"],
    statuses: ["Generated", "Exported", "Archived"],
    reports: ["All Required Management Reports"]
  },
  {
    slug: "admin-settings",
    title: "Admin Settings",
    navLabel: "Settings & Admin",
    icon: Settings,
    summary: "Company profile, departments, locations, shifts, roles, permissions, ticket centers, workflows, approval rules, exports, integrations, and reset protections.",
    owner: "Global Admin / CEO",
    primaryAction: "Update Setting",
    secondaryAction: "Review Audit Log",
    metricLabels: ["Departments", "Roles", "Templates", "Integrations"],
    workflows: ["Manage roles", "Manage templates", "Configure approvals", "Manage safe exports"],
    fields: ["setting key", "value", "department", "owner", "updated by", "audit trail"],
    statuses: ["Active", "Needs Review", "Archived"],
    reports: ["Admin Configuration Export", "Audit Log Report"]
  },
  {
    slug: "audit-log",
    title: "Audit Log",
    navLabel: "Audit Log",
    icon: ShieldCheck,
    summary: "Managerial accountability trail for sensitive actions, approvals, exports, overrides, file uploads, workflow changes, and administrative actions.",
    owner: "Global Admin / CEO",
    primaryAction: "Search Audit Log",
    secondaryAction: "Export Audit History",
    metricLabels: ["Sensitive actions", "Overrides", "Exports", "Failed attempts"],
    workflows: ["Record action", "Filter by entity", "Review override reason", "Export internal history"],
    fields: ["actor", "action", "entity type", "entity ID", "outcome", "reason", "timestamp"],
    statuses: ["SUCCESS", "DENIED", "FAILED"],
    reports: ["Audit Log Report", "Export History Record"]
  },
  {
    slug: "workplace-readiness",
    title: "Workplace Readiness",
    navLabel: "Workplace Readiness",
    icon: HardHat,
    summary: "Readiness view for workspace, equipment, badge/key, uniform/PPE, software coordination, and first-day operational setup.",
    owner: "Manager, Facilities, IT, HR",
    primaryAction: "Create Readiness Task",
    secondaryAction: "Review Blockers",
    metricLabels: ["Ready", "Pending", "Blocked", "Due before start"],
    workflows: ["Assign workspace", "Request badge/key", "Prepare equipment", "Confirm first-day readiness"],
    fields: ["employee", "onboarding case", "workspace", "equipment", "badge/key", "owner", "status"],
    statuses: ["Not Started", "In Progress", "Blocked", "Ready", "Complete"],
    reports: ["First-Day Readiness Report", "Onboarding Readiness Report"]
  },
  {
    slug: "maintenance-operations",
    title: "Maintenance Operations",
    navLabel: "Maintenance Ops",
    icon: Wrench,
    summary: "Maintenance work requests, urgent downtime visibility, preventive checklist coordination, supplies needed, and unresolved blocker escalation.",
    owner: "Maintenance Manager",
    primaryAction: "Create Maintenance Ticket",
    secondaryAction: "Escalate Downtime",
    metricLabels: ["Machine issues", "Facility repairs", "Urgent downtime", "Preventive items"],
    workflows: ["Open maintenance ticket", "Assign owner", "Track downtime", "Close with resolution"],
    fields: ["machine", "area", "priority", "requested by", "owner", "due date", "resolution notes"],
    statuses: ["New", "Assigned", "In Progress", "Blocked", "Resolved", "Closed"],
    reports: ["Maintenance Ticket Backlog", "Open Work Stoppage Report"]
  },
  {
    slug: "capacity-mps",
    title: "Capacity & Master Production Schedule",
    navLabel: "Capacity & MPS",
    icon: Gauge,
    summary: "Manufacturing capacity intelligence. Upload available-hours and load spreadsheets, see work-center utilization heatmaps, gauges, customer load, and work-order schedule. Merged from Scheduling and AdvancedCapacity.",
    owner: "Operations Director",
    primaryAction: "Upload Capacity",
    secondaryAction: "Upload Load",
    metricLabels: ["Work centers", "Months horizon", "Total load hrs", "Overloaded WCs"],
    workflows: ["Excel capacity upload", "Excel load upload", "Heatmap drill-down", "Customer load review"],
    fields: ["work center", "type", "axis", "month", "capacity", "load", "utilization"],
    statuses: ["Available", "Loaded", "Overloaded", "Idle"],
    reports: ["Capacity Utilization Report", "Work-Order Schedule Report", "Customer Load Report"]
  },
  {
    slug: "first-piece-runs",
    title: "First-Piece & Run Tracker",
    navLabel: "First Piece / Runs",
    icon: ClipboardCheck,
    summary: "First-piece inspection records and live run status. Pass/fail/pending tracking, defect codes, FPY (first pass yield) computation, operator/manager signoff, print-friendly export, and an optional live shop-floor view.",
    owner: "Quality Manager",
    primaryAction: "Log Inspection",
    secondaryAction: "Print Export",
    metricLabels: ["Entries today", "Pass", "Fail", "FPY %"],
    workflows: ["Add inspection entry", "Edit entry", "Operator signoff", "Manager signoff", "Print export"],
    fields: ["WO", "part", "customer", "work center", "run", "operation", "method", "tech", "status", "result", "defect code", "op start date"],
    statuses: ["Pass", "Fail", "Pending", "Signed Off"],
    reports: ["First-Pass Yield Summary", "Defect-Code Frequency", "Run Status Report"]
  },
  {
    slug: "scheduling-coverage",
    title: "Scheduling & Coverage",
    navLabel: "Scheduling",
    icon: CalendarClock,
    summary: "Team schedules, shift management, time-off visibility, coverage planning, schedule conflict detection, and manager approval routing for shift changes.",
    owner: "Manager",
    primaryAction: "Publish Week",
    secondaryAction: "Resolve Conflict",
    metricLabels: ["Coverage gaps", "Pending swaps", "Time-off conflicts", "Hours scheduled"],
    workflows: ["Publish weekly schedule", "Employee swap request", "Coverage gap alert", "Manager approval"],
    fields: ["employee", "shift", "date", "department", "swap status", "approver"],
    statuses: ["Draft", "Published", "Pending Swap", "Approved", "Conflict"],
    reports: ["Coverage Gap Report", "Shift Schedule Summary", "Swap Approval Report"]
  },
  {
    slug: "npi-projects",
    title: "NPI Project Tracking",
    navLabel: "NPI Projects",
    icon: FolderKanban,
    summary: "New-product introduction projects, milestones, engineering and manufacturing readiness, cross-functional blockers, department ownership, and launch readiness score.",
    owner: "NPI / Operations Director",
    primaryAction: "Create NPI Project",
    secondaryAction: "Update Milestone",
    metricLabels: ["Active projects", "Milestones at risk", "Open blockers", "Avg readiness"],
    workflows: ["Create project", "Set milestones", "Add blocker", "Update readiness", "Department signoff"],
    fields: ["project", "milestone", "owner department", "due date", "blocker", "readiness score"],
    statuses: ["Planning", "Design", "Pre-Production", "Pilot", "Launched", "Blocked"],
    reports: ["NPI Readiness Report", "NPI Blocker Report", "Milestone Status Report"]
  },
  {
    slug: "sales-operations",
    title: "Sales Operations",
    navLabel: "Sales Ops",
    icon: Handshake,
    summary: "Sales pipeline, customer accounts, opportunity tracking, quote/order status, revenue dashboards, and sales tasks. No payment-card flows; quote/order metadata only.",
    owner: "Sales Manager",
    primaryAction: "Create Opportunity",
    secondaryAction: "Add Account",
    metricLabels: ["Open opps", "Pipeline value", "Won this quarter", "At risk"],
    workflows: ["Pipeline staging", "Quote handoff", "Order coordination", "Sales task assignment"],
    fields: ["account", "opportunity", "stage", "owner", "expected close", "value", "status"],
    statuses: ["New", "Qualified", "Proposal", "Negotiation", "Won", "Lost"],
    reports: ["Pipeline Summary", "Opportunity Aging Report", "Account Activity Report"]
  }
];

export const NAVIGATION = [
  "executive-command-dashboard",
  "erp-command-center",
  "customers-parts",
  "quotes-orders",
  "jobs-work-orders",
  "shop-schedule",
  "inventory-materials",
  "purchasing-receiving",
  "shipping",
  "quality-ncrs",
  "shop-floor-control",
  "maintenance-command",
  "shift-handoff",
  "department-ticket-centers",
  "onboarding-case-management",
  "payroll-coordination-center",
  "time-off-request-center",
  "attendance-schedule-issue-center",
  "manager-task-board",
  "recurring-checklist-center",
  "department-productivity-board",
  "approval-queue",
  "reports-exports",
  "admin-settings",
  "employee-directory",
  "audit-log"
] as const;

export const REPORT_TYPES = [
  "Executive Operations Summary",
  "Company Workforce Readiness Brief",
  "Department Health Report",
  "Manager Weekly Summary",
  "Director Oversight Report",
  "Department Ticket Backlog Report",
  "Ticket Aging Report",
  "Ticket Resolution Report",
  "Open Work Stoppage Report",
  "Payroll Coordination Summary",
  "Pending Payroll Approval Report",
  "Payroll Period Readiness Report",
  "Time Correction Report",
  "Time-Off Request Report",
  "Attendance Issue Report",
  "Onboarding Readiness Report",
  "First-Day Readiness Report",
  "First-Week Readiness Report",
  "30/60/90-Day Review Report",
  "Contractor Expiration Report",
  "Employee Lifecycle Report",
  "Manager Follow-Up Report",
  "Blocked Items Report",
  "Escalation Report",
  "Recurring Checklist Completion Report",
  "Department Productivity Report",
  "Employee Task Report",
  "Equipment Request Report",
  "Training Assignment Report",
  "Policy Acknowledgment Report",
  "ERP Operations Summary",
  "Customer Account Report",
  "Part Master Report",
  "Quote Aging Report",
  "Sales Order Readiness Report",
  "Job Backlog Report",
  "Operation Queue Report",
  "Late Work Order Report",
  "Shop Schedule Report",
  "Inventory Summary",
  "Low Stock Report",
  "Purchase Order Report",
  "Receiving Report",
  "Shipment Board Report",
  "Inspection Queue Report",
  "NCR Summary Report",
  "Shop Floor Time Report"
] as const;

export function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
